version: "3"

services:
  nft_tracker:
    container_name: nft_tracker
    build: ./
    image: result/latest
    env_file: ./.env
    environment:
      - DB_URL=$DB_URL
      - DB_DATABASE=$DB_DATABASE
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=27017
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
