version: "3"
services:
   nft_tracker:
      container_name: nft_tracker
      build: ./
      image: result/latest
      environment:
      restart: unless-stopped
      ports:
        - 8080:8080
      environment:
        - NODE_ENV=development
